export const START_SOCKET_CONNECTION = '@@START_SOCKET_CONNECTION';

export const CONNECTED = '@@SOCKET_CONNECTED';
export const DISCONNECT = '@@SOCKET_DISCONNECT';
export const DISCONNECTED = '@@SOCKET_DISCONNECTED';
export const RECONNECTED = '@@SOCKET_RECONNECTED';

export const BEGIN_SUBCRIBE = '@@BEGIN_SUBSCRIBE';
export const END_SUBSCRIBE = '@@END_SUBSCRIBE';
