export const SET_USER_STATE = 'SET_USER_STATE';
export const SET_RESORTS_LIST = 'SET_RESORTS_LIST';
export const UPDATE_RESORTS_LIST = 'UPDATE_RESORTS_LIST';
export const SET_DYNAMIC_ACCOMMODATION = 'SET_DYNAMIC_ACCOMMODATION';
